#if !canImport(ObjectiveC)
import XCTest

extension ArmatureToolsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ArmatureToolsTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ArmatureToolsTests.__allTests__ArmatureToolsTests),
    ]
}
#endif
