#if !canImport(ObjectiveC)
import XCTest

extension ArmatureTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ArmatureTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ArmatureTests.__allTests__ArmatureTests),
    ]
}
#endif
